### ISSUE TITLE
Is there a way to search by organism type or sequence type?

### ISSUE THREAD

**Issue by BrianFoley** [roblanf/PartitionedAlignments#4]
The repository currently seems to list the data sets by author_year.  I only recognize one or two of the authors.  It would be very nice if I could find data sets for "mammals", or "primates" or "vertebrates".  Or maybe find sets with at least 3,000 bases of DNA and not more than 40 taxa.

**Comment by roblanf** [comment]
Hi Brian,

The summary.csv file contains all of this information. When the repo gets large enough, I will organise a proper front end for easy downloading. But until then, the summary.csv file should have everything you need.

Rob
