### ISSUE TITLE
add locus charpartitions

### ISSUE THREAD

**Issue by roblanf** [roblanf/PartitionedAlignments#46]
The point is to add explicit information on every single locus in the dataset. 

At the moment we have 

```
begin SETS;

	[loci]
	CHARSET	COI_1stpos = 1-1592\3;
	CHARSET	COI_2ndpos = 2-1592\3;
	CHARSET	COI_3rdpos = 3-1592\3;
	CHARSET	16S = 1593-3037;

    CHARPARTITION loci = 1:COI_1stpos, 2:COI_2ndpos, 3:COI_3rdpos, 4:16S;

	[genomes]
	CHARSET	mitochondrial_genome = 1-3037;

    CHARPARTITION genomes = 1:mitochondrial_genome;

end;

```

But we should have 

```
begin SETS;

	[partitions]
	CHARSET	COI_1stpos = 1-1592\3;
	CHARSET	COI_2ndpos = 2-1592\3;
	CHARSET	COI_3rdpos = 3-1592\3;
	CHARSET	16S = 1593-3037;

	[loci]
	CHARPARTITION COI = 1:COI_1stpos, 2:COI_2ndpos, 3:COI_3rdpos;
	CHARPARTITION 16S = 1:16S;

	CHARPARTITION loci = 1:COI, 2:16S;

	[genomes]
	CHARPARTITION	mitochondrial_genome = 1:COI, 2:16S;

	CHARPARTITION genomes = 1:mitochondrial_genome;

```

This involves:

* Change current `[loci]` to `[partitions]`
* add a `[loci]` section with one CHARPARTITION for each locus
* make the `loci` CHARPARTITION list the actual loci, not the charsets themselves
* make the `mitochondrial genome` (and other genome) CHARPARTITIONs list the actual loci, not the charsets themselves

**Comment by DS4B-ANU** [comment]
closing because we're going to have separate nexus files
